require("vinh.plugins-setup")
require("vinh.core.options")
require("vinh.core.keymaps")
require("vinh.core.colorscheme")
require("vinh.plugins.comment")
require("vinh.plugins.nvim-tree")
require("vinh.plugins.lualine")
require("vinh.plugins.telescope")
require("vinh.plugins.nvim-cmp")
require("vinh.plugins.lsp.mason")
require("vinh.plugins.lsp.lspsaga")
require("vinh.plugins.lsp.lspconfig")
require("vinh.plugins.lsp.null-ls")
require("vinh.plugins.autopairs")
require("vinh.plugins.treesitter")
require("vinh.plugins.gitsigns")

